/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calc;

/**
 *
 * @author abhi5
 */
import java.util.*;
public class Calc extends javax.swing.JFrame {
//Variable Declaration
 private static String operation="";
  private static int num1=0;
   private static int num2=0;
   private static float res=0;
    
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputText = new javax.swing.JTextField();
        buttonplus = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        buttonminus = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        buttonmul = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonequalto = new javax.swing.JButton();
        buttondiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InputText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        InputText.setPreferredSize(new java.awt.Dimension(60, 50));
        getContentPane().add(InputText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 60));

        buttonplus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonplus.setText("+");
        buttonplus.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonplusActionPerformed(evt);
            }
        });
        getContentPane().add(buttonplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        button4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button4.setText("4");
        button4.setPreferredSize(new java.awt.Dimension(50, 50));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        buttonminus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonminus.setText("-");
        buttonminus.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonminusActionPerformed(evt);
            }
        });
        getContentPane().add(buttonminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button1.setText("1");
        button1.setPreferredSize(new java.awt.Dimension(50, 50));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button2.setText("2");
        button2.setPreferredSize(new java.awt.Dimension(50, 50));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("AC");
        clear.setPreferredSize(new java.awt.Dimension(50, 50));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 60, 60));

        button5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button5.setText("5");
        button5.setPreferredSize(new java.awt.Dimension(50, 50));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        buttonmul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonmul.setText("*");
        buttonmul.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmulActionPerformed(evt);
            }
        });
        getContentPane().add(buttonmul, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        button8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button8.setText("8");
        button8.setPreferredSize(new java.awt.Dimension(50, 50));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        button7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button7.setText("7");
        button7.setPreferredSize(new java.awt.Dimension(50, 50));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        button0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button0.setText("0");
        button0.setPreferredSize(new java.awt.Dimension(50, 50));
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        getContentPane().add(button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 50, -1));

        button3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button3.setText("3");
        button3.setPreferredSize(new java.awt.Dimension(50, 50));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        button6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button6.setText("6");
        button6.setPreferredSize(new java.awt.Dimension(50, 50));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        button9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button9.setText("9");
        button9.setPreferredSize(new java.awt.Dimension(50, 50));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        buttonequalto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonequalto.setText("=");
        buttonequalto.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonequalto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonequaltoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonequalto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, -1));

        buttondiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttondiv.setText("/");
        buttondiv.setPreferredSize(new java.awt.Dimension(50, 50));
        buttondiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondivActionPerformed(evt);
            }
        });
        getContentPane().add(buttondiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
                // TODO add your handling code here:
                InputText.setText(InputText.getText()+button1.getText());
                
    }//GEN-LAST:event_button1ActionPerformed

    private void buttonmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmulActionPerformed
        // TODO add your handling code here:
        operation="*";
        num1=Integer.parseInt(InputText.getText());
        InputText.setText("");
        
    }//GEN-LAST:event_buttonmulActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        InputText.setText(InputText.getText()+button5.getText());
    }//GEN-LAST:event_button5ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        InputText.setText(InputText.getText()+button2.getText());
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        InputText.setText(InputText.getText()+button3.getText());
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        InputText.setText(InputText.getText()+button4.getText());
    }//GEN-LAST:event_button4ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        InputText.setText(InputText.getText()+button6.getText());
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        InputText.setText(InputText.getText()+button7.getText());
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        InputText.setText(InputText.getText()+button8.getText());
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        InputText.setText(InputText.getText()+button9.getText());
    }//GEN-LAST:event_button9ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        InputText.setText(InputText.getText()+button0.getText());
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonplusActionPerformed
        // TODO add your handling code here:
//Add Operation
        operation="+";
        num1=Integer.parseInt(InputText.getText());
        InputText.setText("");
    }//GEN-LAST:event_buttonplusActionPerformed

    private void buttonminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonminusActionPerformed
        // TODO add your handling code here:
//Subtract Operation
        operation="-";
        num1=Integer.parseInt(InputText.getText());
        InputText.setText("");
    }//GEN-LAST:event_buttonminusActionPerformed

    private void buttondivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondivActionPerformed
        // TODO add your handling code here:
//Divide Operation
        operation="/";
        num1=Integer.parseInt(InputText.getText());
        InputText.setText("");
    }//GEN-LAST:event_buttondivActionPerformed

    private void buttonequaltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonequaltoActionPerformed
        // TODO add your handling code here:
//Taking Input from user
        num2=Integer.parseInt(InputText.getText());
        if(operation.equals("+"))
            res=(float)num1+num2;
        if(operation.equals("-"))
            res=(float)num1-num2;
        if(operation.equals("*"))
            res=(float)num1*num2;
        if(operation.equals("/"))
            res=(float)num1/num2;
        InputText.setText(String.valueOf(res));
    }//GEN-LAST:event_buttonequaltoActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        InputText.setText("");
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputText;
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttondiv;
    private javax.swing.JButton buttonequalto;
    private javax.swing.JButton buttonminus;
    private javax.swing.JButton buttonmul;
    private javax.swing.JButton buttonplus;
    private javax.swing.JButton clear;
    // End of variables declaration//GEN-END:variables
}
